// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: url.proto

package url_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UrlV1Client is the client API for UrlV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlV1Client interface {
	GetUrl(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	CreateUrl(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type urlV1Client struct {
	cc grpc.ClientConnInterface
}

func NewUrlV1Client(cc grpc.ClientConnInterface) UrlV1Client {
	return &urlV1Client{cc}
}

func (c *urlV1Client) GetUrl(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/url_v1.UrlV1/GetUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlV1Client) CreateUrl(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/url_v1.UrlV1/CreateUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlV1Server is the server API for UrlV1 service.
// All implementations must embed UnimplementedUrlV1Server
// for forward compatibility
type UrlV1Server interface {
	GetUrl(context.Context, *GetRequest) (*GetResponse, error)
	CreateUrl(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedUrlV1Server()
}

// UnimplementedUrlV1Server must be embedded to have forward compatible implementations.
type UnimplementedUrlV1Server struct {
}

func (UnimplementedUrlV1Server) GetUrl(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUrl not implemented")
}
func (UnimplementedUrlV1Server) CreateUrl(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUrl not implemented")
}
func (UnimplementedUrlV1Server) mustEmbedUnimplementedUrlV1Server() {}

// UnsafeUrlV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlV1Server will
// result in compilation errors.
type UnsafeUrlV1Server interface {
	mustEmbedUnimplementedUrlV1Server()
}

func RegisterUrlV1Server(s grpc.ServiceRegistrar, srv UrlV1Server) {
	s.RegisterService(&UrlV1_ServiceDesc, srv)
}

func _UrlV1_GetUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlV1Server).GetUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/url_v1.UrlV1/GetUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlV1Server).GetUrl(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlV1_CreateUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlV1Server).CreateUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/url_v1.UrlV1/CreateUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlV1Server).CreateUrl(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UrlV1_ServiceDesc is the grpc.ServiceDesc for UrlV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrlV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "url_v1.UrlV1",
	HandlerType: (*UrlV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUrl",
			Handler:    _UrlV1_GetUrl_Handler,
		},
		{
			MethodName: "CreateUrl",
			Handler:    _UrlV1_CreateUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url.proto",
}
